### ISSUE TITLE
Initial Deployment to Heroku

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/hefestus-cave#1]
As a developer, I want to deploy the website to Heroku early so that I can make sure all initial settings are correct.

### Acceptance Criteria
- The project needs to be set up with all the correct settings and files.
- The project needs to be connected to GitHub for easy deployment.

### Tasks
- [x] Create Procfile as per Heroku instructions.
- [x] Create requirements.txt file.
- [x] Add config vars in Heroku project settings.
- [x] Connect the Heroku app with the GitHub repository.
